DATAAREA16	EQU *
CURX            RMB 1       CURSOR COLUMN POSITION (0-50 OR 0-63)
CURY            RMB 1       CURSOR ROW POSITION (0-23)
CURSORCHAR      RMB 1       $81 = BLOCK, $8D = THICK UL
CURSORDELAY     RMB 2
REVERSE         RMB 1       0 = GREEN ON BLACK; 255 = BLACK ON GREEN
CURSORENABLE    RMB 1       0 = NO TEXT CURSOR; 1 = FIXED; 2 = BLINK
HRTEXTWIDTH     RMB 1       HI-RES CHARACTERS PER LINE (51 OR 64 FOR NOW)
FONTLOCATION    RMB 2
CLEARKEYCLEARS  RMB 1       NEXT PRESS OF CLEAR KEY DOES CLS
TIMVALMSW       RMB 2       MSW OF EXTENDED TIMER
DWPRINTER       RMB 1       FLAG FOR DRIVEWIRE PRINTER REDIRECTION
ERRNO           RMB 1       ERROR NUMBER (x2)
ERRLINE         RMB 2       BASIC LINE NUMBER OF ERROR
ONERRSTMT       RMB 2       BASIC LINE NUMBER OF 'ON ERROR' STATEMENT
ONERRTARGET     RMB 2       BASIC LINE NUMBER TO JUMP ON ERROR
TICKSPERSEC     RMB 1       WHAT TO DIVIDE TIMER/TIMERL BY TO GET SECONDS
ALTCOLOR	RMB 1       TEXT MODE COLOR: 0 = GREEN, 8 = ORANGE
FASTMODE	RMB 1       BIT 0 SET: FAST ROM ACCESS MODE (SAM R0, $FFD7)
PREVBEGGRP	RMB 1       START OF VISIBLE WINDOW AT LAST GR-CHAR OUTPUT
* SCRATCHPAD VARIABLES
INQUOTFLAG	EQU DBUF1   FLAG 'WITHIN QUOTES' DURING UNCRUNCH

